export const Actions={
    SIGNIN_REQUEST:"SIGININ+REQUEST",
    SIGNIN_SUCCESS:"SIGIN_SUCCESS",
    SIGNIN_FAILURE:"SIGIN_FAILURE",

    SIGNUP_REQUEST:"SIGINUP_REQUEST",
    SIGNUP_SUCCESS:"SIGUP_SUCCESS",
    SIGNUP_FAILURE:"SIGUP_FAILURE",

    SIGNOUT_REQUEST:"SIGOUT_REQUEST",
    SIGNOUT_SUCCESS:"SIGOUT_SUCCESS",
    SIGNOUT_FAILURE:"SIGOUT_FAILURE"
}